### ISSUE TITLE
🐞 Typo in well-formed spoiled ballot check

### ISSUE THREAD

**Issue by eionblanc** [mitre/ElectionGuardVerifier.jl#1]
**Current Behavior**. In the `check_sum` function of `src/Well_formed_spoiled_ballots.jl`, the conditional to check whether the contest vote count surpasses the number of allowed votes contains a superfluous `then`. Julia interprets `then` as a variable which is, of course, undefined and thus throws an `UndefVarError` whenever the conditional `votes > votes_allowed` is true.

**Expected Behavior**. When `votes > votes_allowed` is true, the verifier should run the following line without error and return `B` to flag failure of verification check (16.B).

**Reproduction**. Run the verifier on any election record containing a spoiled ballot that contains some contest with total votes greater than the count of allowed votes.

**Resolution**. Remove `then` from line 68 of `src/Well_formed_spoiled_ballots.jl`.

**Comment by ramsdell** [comment]
Thank you for the fix.
